services:
# Container Aplikasi (Laravel)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:             # <--- TAMBAHKAN INI
      - "8000:8000"    # <--- DAN INI
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db

  # Container Database (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: digitalisasi_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: